import { useState, useEffect, useCallback } from 'react';
import { CHILD_PROFILES } from '../../lib/profileData';

const DOMAINS = [
  { key: 'identity', label: 'Identity & Judgment', color: '#7c3aed' },
  { key: 'communication', label: 'Communication & Persuasion', color: '#2563eb' },
  { key: 'building', label: 'Building & Entrepreneurship', color: '#d97706' },
  { key: 'humanFluency', label: 'Human Fluency', color: '#db2777' },
  { key: 'aiSystems', label: 'AI & Systems Fluency', color: '#0891b2' },
  { key: 'physical', label: 'Physical Mastery', color: '#16a34a' },
];

const CHILDREN = [
  { id: 'everly', name: 'Everly', agent: 'Vera', color: '#7c3aed' },
  { id: 'isla', name: 'Isla', agent: 'Ren', color: '#dc2626' },
  { id: 'weston', name: 'Weston', agent: 'Ozzy', color: '#16a34a' },
];

interface SessionLog {
  id: string;
  date: string;
  sessionNumber: number;
  workedOn: string;
  avoided: string;
  hardThing: string;
  domainStatus: Record<string, string>;
  connectedToLife: string;
  nextSessionOpens: string;
  autoGenerated: boolean;
  edited: boolean;
}

interface ProfileData {
  profile: any;
  progressions: any;
}

export default function ProfilesProgress({ basePath }: { basePath: string }) {
  const [selectedChild, setSelectedChild] = useState('everly');
  const [activeSection, setActiveSection] = useState<'profile' | 'logs' | 'progressions'>('profile');
  const [profileData, setProfileData] = useState<ProfileData | null>(null);
  const [logs, setLogs] = useState<SessionLog[]>([]);
  const [loading, setLoading] = useState(false);
  const [editingLog, setEditingLog] = useState<string | null>(null);
  const [editDraft, setEditDraft] = useState<Partial<SessionLog>>({});
  const [savingProfile, setSavingProfile] = useState(false);
  const [profileDraft, setProfileDraft] = useState<any>({});
  const [savingProgressions, setSavingProgressions] = useState(false);
  const [progressionDraft, setProgressionDraft] = useState<any>({});

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const [profRes, logsRes] = await Promise.all([
        fetch(`${basePath}/forge-api/admin/profile/${selectedChild}`),
        fetch(`${basePath}/forge-api/admin/session-logs/${selectedChild}`)
      ]);
      const profJson = await profRes.json();
      const logsJson = await logsRes.json();
      const identity = profJson.profile?.identityFile || {};
      if (!identity.agentName && CHILD_PROFILES[selectedChild]) {
        const seed = CHILD_PROFILES[selectedChild].identityFile;
        await fetch(`${basePath}/forge-api/admin/profile/${selectedChild}`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ identityFile: seed })
        });
        const reRes = await fetch(`${basePath}/forge-api/admin/profile/${selectedChild}`);
        const reJson = await reRes.json();
        setProfileData(reJson);
        setProfileDraft(reJson.profile?.identityFile || {});
        setProgressionDraft(reJson.progressions || {});
      } else {
        setProfileData(profJson);
        setProfileDraft(identity);
        setProgressionDraft(profJson.progressions || {});
      }
      setLogs(logsJson.logs || []);
    } catch (e) {
      console.error(e);
    }
    setLoading(false);
  }, [selectedChild, basePath]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const saveProfile = async () => {
    setSavingProfile(true);
    await fetch(`${basePath}/forge-api/admin/profile/${selectedChild}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ identityFile: profileDraft })
    });
    setSavingProfile(false);
    fetchData();
  };

  const saveProgressions = async () => {
    setSavingProgressions(true);
    await fetch(`${basePath}/forge-api/admin/progressions/${selectedChild}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(progressionDraft)
    });
    setSavingProgressions(false);
    fetchData();
  };

  const saveLogEdit = async (logId: string) => {
    await fetch(`${basePath}/forge-api/admin/session-logs/${selectedChild}/${logId}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(editDraft)
    });
    setEditingLog(null);
    fetchData();
  };

  const child = CHILDREN.find(c => c.id === selectedChild)!;

  return (
    <div style={{ padding: '1.5rem', maxWidth: 900 }}>
      <div style={{ display: 'flex', gap: 12, marginBottom: 24 }}>
        {CHILDREN.map(c => (
          <button key={c.id} onClick={() => setSelectedChild(c.id)}
            style={{ padding: '8px 20px', borderRadius: 8, border: selectedChild === c.id ? `2px solid ${c.color}` : '1px solid #e5e7eb',
              background: selectedChild === c.id ? c.color + '15' : 'white', fontWeight: selectedChild === c.id ? 500 : 400,
              cursor: 'pointer', color: selectedChild === c.id ? c.color : '#374151' }}>
            {c.name} <span style={{ fontSize: 12, opacity: 0.7 }}>/ {c.agent}</span>
          </button>
        ))}
      </div>

      <div style={{ display: 'flex', gap: 8, marginBottom: 24, borderBottom: '1px solid #e5e7eb', paddingBottom: 12 }}>
        {(['profile', 'logs', 'progressions'] as const).map(s => (
          <button key={s} onClick={() => setActiveSection(s)}
            style={{ padding: '6px 16px', borderRadius: 6, border: 'none', cursor: 'pointer',
              background: activeSection === s ? child.color : 'transparent',
              color: activeSection === s ? 'white' : '#6b7280', fontWeight: activeSection === s ? 500 : 400,
              fontSize: 14, textTransform: 'capitalize' }}>
            {s === 'logs' ? 'Session Logs' : s === 'progressions' ? 'Progressions' : 'Profile'}
          </button>
        ))}
      </div>

      {loading && <div style={{ color: '#9ca3af', fontSize: 14 }}>Loading...</div>}

      {!loading && activeSection === 'profile' && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <ProfileField label="Agent" value={profileDraft.agentName || ''} onChange={v => setProfileDraft((d: any) => ({...d, agentName: v}))} />
          <ProfileField label="Age" value={profileDraft.age || ''} onChange={v => setProfileDraft((d: any) => ({...d, age: v}))} />
          <ProfileField label="Developmental stage" value={profileDraft.stageLabel || ''} onChange={v => setProfileDraft((d: any) => ({...d, stageLabel: v}))} />
          <ProfileFieldLong label="Stage description (agent voice)" value={profileDraft.stageDescription || ''} onChange={v => setProfileDraft((d: any) => ({...d, stageDescription: v}))} />
          <ProfileFieldLong label="S2S findings (plain language)" value={profileDraft.s2sFindings || ''} onChange={v => setProfileDraft((d: any) => ({...d, s2sFindings: v}))} />
          <ProfileFieldLong label="What actually motivates them" value={profileDraft.motivations || ''} onChange={v => setProfileDraft((d: any) => ({...d, motivations: v}))} />
          <ProfileFieldLong label="Avoidance patterns" value={profileDraft.avoidancePatterns || ''} onChange={v => setProfileDraft((d: any) => ({...d, avoidancePatterns: v}))} />
          <div style={{ background: '#f9fafb', borderRadius: 8, padding: 16, border: '1px solid #e5e7eb' }}>
            <div style={{ fontSize: 12, fontWeight: 500, color: '#6b7280', marginBottom: 12, textTransform: 'uppercase', letterSpacing: '0.05em' }}>Connected context</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              <ProfileField label="Speech case topic" value={profileDraft.connectedContext?.speechCaseTopic || ''} onChange={v => setProfileDraft((d: any) => ({...d, connectedContext: {...(d.connectedContext||{}), speechCaseTopic: v}}))} />
              <ProfileField label="Thrive current unit" value={profileDraft.connectedContext?.thriveCurrentUnit || ''} onChange={v => setProfileDraft((d: any) => ({...d, connectedContext: {...(d.connectedContext||{}), thriveCurrentUnit: v}}))} />
              <ProfileField label="S2S current focus" value={profileDraft.connectedContext?.s2sFocus || ''} onChange={v => setProfileDraft((d: any) => ({...d, connectedContext: {...(d.connectedContext||{}), s2sFocus: v}}))} />
              <ProfileField label="Coach Dillon focus" value={profileDraft.connectedContext?.coachFocus || ''} onChange={v => setProfileDraft((d: any) => ({...d, connectedContext: {...(d.connectedContext||{}), coachFocus: v}}))} />
            </div>
          </div>
          <button onClick={saveProfile} disabled={savingProfile}
            style={{ alignSelf: 'flex-start', padding: '10px 24px', background: child.color, color: 'white', border: 'none', borderRadius: 8, cursor: 'pointer', fontWeight: 500 }}>
            {savingProfile ? 'Saving...' : 'Save profile'}
          </button>
        </div>
      )}

      {!loading && activeSection === 'logs' && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          {logs.length === 0 && <div style={{ color: '#9ca3af', fontSize: 14 }}>No session logs yet. Logs are auto-generated at the end of each Forge session.</div>}
          {logs.map(log => (
            <div key={log.id} style={{ background: 'white', border: '1px solid #e5e7eb', borderRadius: 10, padding: 16 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
                <div>
                  <span style={{ fontWeight: 500, fontSize: 15 }}>Session {log.sessionNumber}</span>
                  <span style={{ marginLeft: 10, fontSize: 12, color: '#9ca3af' }}>{new Date(log.date).toLocaleDateString()}</span>
                  {log.autoGenerated && !log.edited && <span style={{ marginLeft: 8, fontSize: 11, background: '#dbeafe', color: '#1e40af', padding: '2px 8px', borderRadius: 4 }}>auto</span>}
                  {log.edited && <span style={{ marginLeft: 8, fontSize: 11, background: '#d1fae5', color: '#065f46', padding: '2px 8px', borderRadius: 4 }}>edited</span>}
                </div>
                {editingLog !== log.id && (
                  <button onClick={() => { setEditingLog(log.id); setEditDraft(log); }}
                    style={{ fontSize: 12, color: '#6b7280', background: 'none', border: '1px solid #e5e7eb', borderRadius: 6, padding: '4px 12px', cursor: 'pointer' }}>
                    Edit
                  </button>
                )}
              </div>
              {editingLog === log.id ? (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                  <LogField label="What we worked on" value={editDraft.workedOn || ''} onChange={v => setEditDraft(d => ({...d, workedOn: v}))} />
                  <LogField label="What she avoided and how" value={editDraft.avoided || ''} onChange={v => setEditDraft(d => ({...d, avoided: v}))} />
                  <LogField label="One thing she did that was hard" value={editDraft.hardThing || ''} onChange={v => setEditDraft(d => ({...d, hardThing: v}))} />
                  <LogField label="Connected to life" value={editDraft.connectedToLife || ''} onChange={v => setEditDraft(d => ({...d, connectedToLife: v}))} />
                  <LogField label="Next session opens with" value={editDraft.nextSessionOpens || ''} onChange={v => setEditDraft(d => ({...d, nextSessionOpens: v}))} />
                  <div style={{ display: 'flex', gap: 8, marginTop: 4 }}>
                    <button onClick={() => saveLogEdit(log.id)} style={{ padding: '6px 16px', background: child.color, color: 'white', border: 'none', borderRadius: 6, cursor: 'pointer', fontSize: 13 }}>Save</button>
                    <button onClick={() => setEditingLog(null)} style={{ padding: '6px 16px', background: '#f3f4f6', color: '#374151', border: 'none', borderRadius: 6, cursor: 'pointer', fontSize: 13 }}>Cancel</button>
                  </div>
                </div>
              ) : (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                  <LogRow label="Worked on" value={log.workedOn} />
                  <LogRow label="Avoided" value={log.avoided} color="#dc2626" />
                  <LogRow label="Did hard thing" value={log.hardThing} color="#16a34a" />
                  <LogRow label="Connected to life" value={log.connectedToLife} />
                  <LogRow label="Next session" value={log.nextSessionOpens} color="#7c3aed" />
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {!loading && activeSection === 'progressions' && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
          <p style={{ fontSize: 13, color: '#6b7280', marginBottom: 4 }}>Set quarterly destinations and current units for each domain. These feed directly into what Vera, Ren, and Ozzy build toward each session.</p>
          {DOMAINS.map(domain => (
            <div key={domain.key} style={{ background: 'white', border: '1px solid #e5e7eb', borderRadius: 10, padding: 16 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
                <div style={{ width: 10, height: 10, borderRadius: '50%', background: domain.color }} />
                <span style={{ fontWeight: 500, fontSize: 14 }}>{domain.label}</span>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                <ProgField label="Q1 destination (capability goal)"
                  value={progressionDraft.q1Destinations?.[domain.key] || ''}
                  onChange={v => setProgressionDraft((d: any) => ({...d, q1Destinations: {...(d.q1Destinations||{}), [domain.key]: v}}))} />
                <ProgField label="Current unit"
                  value={progressionDraft.currentUnits?.[domain.key] || ''}
                  onChange={v => setProgressionDraft((d: any) => ({...d, currentUnits: {...(d.currentUnits||{}), [domain.key]: v}}))} />
                <ProgField label="Milestone markers (observable behaviors, comma separated)"
                  value={progressionDraft.milestones?.[domain.key] || ''}
                  onChange={v => setProgressionDraft((d: any) => ({...d, milestones: {...(d.milestones||{}), [domain.key]: v}}))} />
              </div>
            </div>
          ))}
          <button onClick={saveProgressions} disabled={savingProgressions}
            style={{ alignSelf: 'flex-start', padding: '10px 24px', background: child.color, color: 'white', border: 'none', borderRadius: 8, cursor: 'pointer', fontWeight: 500 }}>
            {savingProgressions ? 'Saving...' : 'Save progressions'}
          </button>
        </div>
      )}
    </div>
  );
}

function ProfileField({ label, value, onChange }: { label: string; value: any; onChange: (v: string) => void }) {
  return (
    <div>
      <div style={{ fontSize: 12, color: '#6b7280', marginBottom: 4 }}>{label}</div>
      <input value={value} onChange={e => onChange(e.target.value)}
        style={{ width: '100%', padding: '8px 10px', border: '1px solid #e5e7eb', borderRadius: 6, fontSize: 14, boxSizing: 'border-box' }} />
    </div>
  );
}

function ProfileFieldLong({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) {
  return (
    <div>
      <div style={{ fontSize: 12, color: '#6b7280', marginBottom: 4 }}>{label}</div>
      <textarea value={value} onChange={e => onChange(e.target.value)} rows={3}
        style={{ width: '100%', padding: '8px 10px', border: '1px solid #e5e7eb', borderRadius: 6, fontSize: 14, resize: 'vertical', boxSizing: 'border-box' }} />
    </div>
  );
}

function LogField({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) {
  return (
    <div>
      <div style={{ fontSize: 11, color: '#9ca3af', marginBottom: 3 }}>{label}</div>
      <textarea value={value} onChange={e => onChange(e.target.value)} rows={2}
        style={{ width: '100%', padding: '6px 8px', border: '1px solid #e5e7eb', borderRadius: 6, fontSize: 13, resize: 'vertical', boxSizing: 'border-box' }} />
    </div>
  );
}

function LogRow({ label, value, color }: { label: string; value: string; color?: string }) {
  if (!value) return null;
  return (
    <div style={{ display: 'flex', gap: 8 }}>
      <span style={{ fontSize: 11, color: '#9ca3af', minWidth: 90, paddingTop: 2 }}>{label}</span>
      <span style={{ fontSize: 13, color: color || '#374151', flex: 1 }}>{value}</span>
    </div>
  );
}

function ProgField({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) {
  return (
    <div>
      <div style={{ fontSize: 11, color: '#9ca3af', marginBottom: 3 }}>{label}</div>
      <input value={value} onChange={e => onChange(e.target.value)}
        style={{ width: '100%', padding: '7px 10px', border: '1px solid #e5e7eb', borderRadius: 6, fontSize: 13, boxSizing: 'border-box' }} />
    </div>
  );
}
